## Data Analysis with Python: Zero to Pandas - Course Project Guidelines
#### (remove this cell before submission)
<a target="_blank" href="https://colab.research.google.com/github/JovianHQ/notebooks/blob/main/data-analysis-with-python-zero-to-pandas/course-project/zerotopandas-course-project-starter.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

This is the starter notebook for the course project for [Data Analysis with Python: Zero to Pandas](https://jovian.com/learn/data-analysis-with-python-zero-to-pandas). You will pick a real-world dataset of your choice and apply the concepts learned in this course to perform exploratory data analysis. Use this starter notebook as an outline for your project . Focus on documentation and presentation - this Jupyter notebook will also serve as a project report, so make sure to include detailed explanations wherever possible using Markdown cells.


This is an executable [Jupyter notebook](https://jupyter.org). Click the **Open in Colab** button at the top of this page to execute the code. Then, click the "Copy to Drive" button in the Google Colab toolbar to save a copy of the notebook in your Google Drive.


### Evaluation Criteria

Your submission will be evaluated using the following criteria:

* Dataset must contain at least 3 columns and 150 rows of data
* You must ask and answer at least 5 questions about the dataset
* Your submission must include at least 5 visualizations (graphs)
* Your submission must include explanations using markdown cells, apart from the code.
* Your work must not be plagiarized i.e. copy-pasted for somewhere else.


Follow this step-by-step guide to work on your project.


### Step 1: Select a real-world dataset

- Find an interesting dataset on this page: https://www.kaggle.com/datasets?fileType=csv
- The data should be in CSV format, and should contain at least 3 columns and 150 rows
- Download the dataset using the [`opendatasets` Python library](https://github.com/JovianML/opendatasets#opendatasets)

Here's some sample code for downloading the [US Elections Dataset](https://www.kaggle.com/tunguz/us-elections-dataset):

```
import opendatasets as od
dataset_url = 'https://www.kaggle.com/tunguz/us-elections-dataset'
od.download('https://www.kaggle.com/tunguz/us-elections-dataset')
```

### Step 2: Perform data preparation & cleaning

- Load the dataset into a data frame using Pandas
- Explore the number of rows & columns, ranges of values etc.
- Handle missing, incorrect and invalid data
- Perform any additional steps (parsing dates, creating additional columns, merging multiple dataset etc.)


### Step 3: Perform exploratory analysis & visualization

- Compute the mean, sum, range and other interesting statistics for numeric columns
- Explore distributions of numeric columns using histograms etc.
- Explore relationship between columns using scatter plots, bar charts etc.
- Make a note of interesting insights from the exploratory analysis

### Step 4: Ask & answer questions about the data

- Ask at least 5 interesting questions about your dataset
- Answer the questions either by computing the results using Numpy/Pandas or by plotting graphs using Matplotlib/Seaborn
- Create new columns, merge multiple dataset and perform grouping/aggregation wherever necessary
- Wherever you're using a library function from Pandas/Numpy/Matplotlib etc. explain briefly what it does


### Step 5: Summarize your inferences & write a conclusion

- Write a summary of what you've learned from the analysis
- Include interesting insights and graphs from previous sections
- Share ideas for future work on the same topic using other relevant datasets
- Share links to resources you found useful during your analysis


### Step 6: Make a submission & share your work

- To save your work, select "File" > "Save a Copy in Drive" on Google Colab. Once the copy is created, click the "Share" button and select "Anyone with the link" under the "General Access" section to make this notebook publicly accessible.
- Go to the submission page and submit a link to your colab notebook.
- **Link of submission page**: https://jovian.com/learn/data-analysis-with-python-zero-to-pandas/assignment/course-project

### (Optional) Step 7: Write a blog post

- A blog post is a great way to present and showcase your work.  
- Sign up on [Medium.com](https://medium.com) to write a blog post for your project.
- Copy over the explanations from your Jupyter notebook into your blog post, and [embed code cells & outputs](https://medium.com/jovianml/share-and-embed-jupyter-notebooks-online-with-jovian.com-df709a03064e)
- Check out the Jovian.ml Medium publication for inspiration: https://medium.com/jovianml





### Example Projects

Refer to these projects for inspiration:

* [Analyzing your browser history using Pandas & Seaborn](https://medium.com/free-code-camp/understanding-my-browsing-pattern-using-pandas-and-seaborn-162b97e33e51) by Kartik Godawat

* [Understanding the Gender Divide in Data Science Roles](https://medium.com/datadriveninvestor/exploratory-data-analysis-eda-understanding-the-gender-divide-in-data-science-roles-9faa5da44f5b) by Aakanksha N S

* [2019 State of Javscript Survey Results](https://2019.stateofjs.com/demographics/)

* [2020 Stack Overflow Developer Survey Results](https://insights.stackoverflow.com/survey/2020)

**NOTE**: Remove this cell containing the instructions before making your submission. You can do using the "Edit > Delete Cells" menu option.

# Project Title - change this

TODO - Write some introduction about your project here: describe the dataset, where you got it from, what you're trying to do with it, and which tools & techniques you're using. You can also mention about the course [Data Analysis with Python: Zero to Pandas](zerotopandas.com), and what you've learned from it.

In [1]:
!pip install opendatasets --upgrade --quiet

Let's begin by downloading the data, and listing the files within the dataset.

In [2]:
# my data set
dataset_url = 'https://www.kaggle.com/datasets/samartalwar/sleep-debt-and-screen-time-late-night-phone-habits/data'

In [5]:
import opendatasets as od
od.download(dataset_url)

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username: xanderlsh95
Your Kaggle Key: ··········
Dataset URL: https://www.kaggle.com/datasets/samartalwar/sleep-debt-and-screen-time-late-night-phone-habits
Downloading sleep-debt-and-screen-time-late-night-phone-habits.zip to ./sleep-debt-and-screen-time-late-night-phone-habits

100%|██████████| 206k/206k [00:00<00:00, 57.7MB/s]

The dataset has been downloaded and extracted.

In [6]:
# Change this
data_dir = './sleep-debt-and-screen-time-late-night-phone-habits'

In [7]:
import os
os.listdir(data_dir)

['bedtime_screentime_sleep_debt.csv']

## Data Preparation and Cleaning

Modern sleep architecture is severely disrupted by late-night digital consumption. Dopaminergic hyper-arousal from short-form video (TikTok, Reels) and melatonin suppression from unmitigated blue light exposure directly compound into chronic sleep debt and elevated next-day fatigue.

This dataset provides cross-sectional lifestyle telemetry for 8,500 individuals, mapping their evening tech habits, caffeine intake, and demographic chronotypes against physiological sleep metrics and resulting fatigue scores.

> Instructions (delete this cell):
>
> - Load the dataset into a data frame using Pandas
> - Explore the number of rows & columns, ranges of values etc.
> - Handle missing, incorrect and invalid data
> - Perform any additional steps (parsing dates, creating additional columns, merging multiple dataset etc.)

In [8]:

import pandas as pd

In [11]:
sleep_df = pd.read_csv('sleep-debt-and-screen-time-late-night-phone-habits/bedtime_screentime_sleep_debt.csv')

In [12]:
sleep_df

,user_id,age,gender,occupation_type,chronotype,bedtime_phone_minutes,primary_bedtime_app,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score,sleep_debt_category
0,USR-00001,29,Female,Healthcare / Shift Worker,Intermediate,179,Instagram / Reddit,54,1,0,21,84.4,3.20,23.5,22.2,7,10.0,Severe Sleep Debt
1,USR-00002,58,Female,Student,Intermediate,163,YouTube,76,1,92,72,86.7,4.06,18.0,21.5,7,10.0,Severe Sleep Debt
2,USR-00003,41,Female,Healthcare / Shift Worker,Night Owl,100,TikTok / Reels,59,0,45,23,70.5,3.20,18.1,20.5,7,10.0,Severe Sleep Debt
3,USR-00004,36,Non-Binary,Remote Tech,Intermediate,34,YouTube,52,0,97,49,38.1,6.99,21.6,22.4,1,1.7,Mild Deficit
4,USR-00005,23,Female,Healthcare / Shift Worker,Intermediate,27,TikTok / Reels,82,1,0,38,32.3,4.58,24.1,22.8,4,5.3,Moderate Debt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8495,USR-08496,61,Female,Remote Tech,Night Owl,18,Streaming (Netflix/Hulu),61,1,60,74,21.0,5.57,26.5,18.1,3,3.2,Moderate Debt
8496,USR-08497,64,Male,Student,Night Owl,138,TikTok / Reels,58,1,0,58,84.3,3.99,20.4,19.4,7,10.0,Severe Sleep Debt
8497,USR-08498,34,Male,Corporate 9-to-5,Intermediate,56,Streaming (Netflix/Hulu),56,0,94,33,40.6,7.58,17.4,20.7,2,3.7,Mild Deficit
8498,USR-08499,23,Male,Healthcare / Shift Worker,Night Owl,165,TikTok / Reels,72,0,0,52,123.3,3.20,14.2,15.8,7,10.0,Severe Sleep Debt
8499,USR-08500,27,Female,Student,Night Owl,108,Instagram / Reddit,35,1,0,23,55.7,4.04,27.3,18.7,5,6.7,Moderate Debt

In [13]:
sleep_df.columns

Index(['user_id', 'age', 'gender', 'occupation_type', 'chronotype',
       'bedtime_phone_minutes', 'primary_bedtime_app', 'screen_brightness_pct',
       'blue_light_filter_active', 'caffeine_post_5pm_mg',
       'physical_activity_min', 'sleep_latency_min', 'total_sleep_hours',
       'deep_sleep_pct', 'rem_sleep_pct', 'morning_alarm_snoozes',
       'next_day_fatigue_score', 'sleep_debt_category'],
      dtype='object')

In [14]:
sleep_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8500 non-null   object
 1   age                       8500 non-null   int64
 2   gender                    8500 non-null   object
 3   occupation_type           8500 non-null   object
 4   chronotype                8500 non-null   object
 5   bedtime_phone_minutes     8500 non-null   int64
 6   primary_bedtime_app       8500 non-null   object
 7   screen_brightness_pct     8500 non-null   int64
 8   blue_light_filter_active  8500 non-null   int64
 9   caffeine_post_5pm_mg      8500 non-null   int64
 10  physical_activity_min     8500 non-null   int64
 11  sleep_latency_min         8500 non-null   float64
 12  total_sleep_hours         8500 non-null   float64
 13  deep_sleep_pct            8500 non-null   float64
 14  rem_sleep_pct             8500 non-null   float64
 15  morning_alarm_snoozes     8500 non-null   int64
 16  next_day_fatigue_score    8500 non-null   float64
 17  sleep_debt_category       8500 non-null   object
dtypes: float64(5), int64(7), object(6)
memory usage: 1.2+ MB

In [20]:
sleep_df.describe()

,age,bedtime_phone_minutes,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score
count,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000
mean,34.355647,59.250000,55.153882,0.467765,33.222471,35.701412,40.671471,6.266209,21.735741,19.105859,2.766000,3.794671
std,11.584259,36.931991,19.850550,0.498989,51.935645,20.819390,17.444914,1.446258,3.069377,2.546459,1.695407,2.685153
min,18.000000,1.000000,10.000000,0.000000,0.000000,0.000000,6.000000,3.200000,8.100000,9.600000,0.000000,1.000000
25%,25.000000,31.000000,42.000000,0.000000,0.000000,21.000000,28.200000,5.240000,19.700000,17.400000,2.000000,1.100000
50%,32.000000,51.000000,55.000000,0.000000,0.000000,35.000000,37.600000,6.330000,21.900000,19.100000,3.000000,3.200000
75%,42.000000,79.000000,69.000000,1.000000,55.000000,50.000000,49.700000,7.350000,23.900000,20.800000,4.000000,5.600000
max,65.000000,180.000000,100.000000,1.000000,250.000000,112.000000,123.300000,9.800000,28.000000,27.000000,7.000000,10.000000

In [19]:
sleep_df.describe(include='all')

,user_id,age,gender,occupation_type,chronotype,bedtime_phone_minutes,primary_bedtime_app,screen_brightness_pct,blue_light_filter_active,caffeine_post_5pm_mg,physical_activity_min,sleep_latency_min,total_sleep_hours,deep_sleep_pct,rem_sleep_pct,morning_alarm_snoozes,next_day_fatigue_score,sleep_debt_category
count,8500,8500.000000,8500,8500,8500,8500.000000,8500,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500.000000,8500
unique,8500,NaN,3,5,3,NaN,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
top,USR-08500,NaN,Female,Corporate 9-to-5,Intermediate,NaN,TikTok / Reels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate Debt
freq,1,NaN,4347,2838,3880,NaN,2198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4462
mean,NaN,34.355647,NaN,NaN,NaN,59.250000,NaN,55.153882,0.467765,33.222471,35.701412,40.671471,6.266209,21.735741,19.105859,2.766000,3.794671,NaN
std,NaN,11.584259,NaN,NaN,NaN,36.931991,NaN,19.850550,0.498989,51.935645,20.819390,17.444914,1.446258,3.069377,2.546459,1.695407,2.685153,NaN
min,NaN,18.000000,NaN,NaN,NaN,1.000000,NaN,10.000000,0.000000,0.000000,0.000000,6.000000,3.200000,8.100000,9.600000,0.000000,1.000000,NaN
25%,NaN,25.000000,NaN,NaN,NaN,31.000000,NaN,42.000000,0.000000,0.000000,21.000000,28.200000,5.240000,19.700000,17.400000,2.000000,1.100000,NaN
50%,NaN,32.000000,NaN,NaN,NaN,51.000000,NaN,55.000000,0.000000,0.000000,35.000000,37.600000,6.330000,21.900000,19.100000,3.000000,3.200000,NaN
75%,NaN,42.000000,NaN,NaN,NaN,79.000000,NaN,69.000000,1.000000,55.000000,50.000000,49.700000,7.350000,23.900000,20.800000,4.000000,5.600000,NaN
max,NaN,65.000000,NaN,NaN,NaN,180.000000,NaN,100.000000,1.000000,250.000000,112.000000,123.300000,9.800000,28.000000,27.000000,7.000000,10.000000,NaN

In [17]:
sleep_df.shape

(8500, 18)

In [18]:
sleep_copy_df = sleep_df.copy()

In [ ]:
sleep_copy_df

In [23]:
primary_bedtime_app = sleep_copy_df['primary_bedtime_app'].nunique()

In [30]:
sleep_copy_df['bedtime_phone_minutes'] = pd.to_numeric(sleep_copy_df['bedtime_phone_minutes'], errors='coerce')

In [27]:
sleep_copy_df['primary_bedtime_app'].value_counts()

primary_bedtime_app
TikTok / Reels              2198
YouTube                     1928
Instagram / Reddit          1630
Streaming (Netflix/Hulu)    1301
Messaging / Chat             847
News / Reading               596
Name: count, dtype: int64

Find out if there's any missing rows

In [31]:

import numpy as np

In [40]:
#this is finding percentage of missing rows in each column
missing_ratio = sleep_copy_df.isna().mean() * 100
missing_ratio

user_id                     0.0
age                         0.0
gender                      0.0
occupation_type             0.0
chronotype                  0.0
bedtime_phone_minutes       0.0
primary_bedtime_app         0.0
screen_brightness_pct       0.0
blue_light_filter_active    0.0
caffeine_post_5pm_mg        0.0
physical_activity_min       0.0
sleep_latency_min           0.0
total_sleep_hours           0.0
deep_sleep_pct              0.0
rem_sleep_pct               0.0
morning_alarm_snoozes       0.0
next_day_fatigue_score      0.0
sleep_debt_category         0.0
dtype: float64

According to above, there's no missing rows.

In [41]:
#this is counting all non-null/valid entries down each column (which defaults to axis=0). Because .isna() replaces values with True and False (neither of which are NaN), .count() treats every single one of them as valid and returns the total row count (8,500) for every column.
missing_num = sleep_copy_df.isna().count()
missing_num

user_id                     8500
age                         8500
gender                      8500
occupation_type             8500
chronotype                  8500
bedtime_phone_minutes       8500
primary_bedtime_app         8500
screen_brightness_pct       8500
blue_light_filter_active    8500
caffeine_post_5pm_mg        8500
physical_activity_min       8500
sleep_latency_min           8500
total_sleep_hours           8500
deep_sleep_pct              8500
rem_sleep_pct               8500
morning_alarm_snoozes       8500
next_day_fatigue_score      8500
sleep_debt_category         8500
dtype: int64

In [37]:
heavy_missing_cols = missing_ratio[missing_ratio > 30]
heavy_missing_cols

Series([], dtype: float64)

In [42]:
# This will correctly return the number of missing rows per column
missing_num2 = sleep_copy_df.isna().sum()
print(missing_num2)

user_id                     0
age                         0
gender                      0
occupation_type             0
chronotype                  0
bedtime_phone_minutes       0
primary_bedtime_app         0
screen_brightness_pct       0
blue_light_filter_active    0
caffeine_post_5pm_mg        0
physical_activity_min       0
sleep_latency_min           0
total_sleep_hours           0
deep_sleep_pct              0
rem_sleep_pct               0
morning_alarm_snoozes       0
next_day_fatigue_score      0
sleep_debt_category         0
dtype: int64

## Exploratory Analysis and Visualization

**TODO** - write some explanation here.

> Instructions (delete this cell)
>
> - Compute the mean, sum, range and other interesting statistics for numeric columns
> - Explore distributions of numeric columns using histograms etc.
> - Explore relationship between columns using scatter plots, bar charts etc.
> - Make a note of interesting insights from the exploratory analysis

Let's begin by importing`matplotlib.pyplot` and `seaborn`.

In [ ]:
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

sns.set_style('darkgrid')
matplotlib.rcParams['font.size'] = 14
matplotlib.rcParams['figure.figsize'] = (9, 5)
matplotlib.rcParams['figure.facecolor'] = '#00000000'

**TODO** - Explore one or more columns by plotting a graph below, and add some explanation about it

**TODO** - Explore one or more columns by plotting a graph below, and add some explanation about it

**TODO** - Explore one or more columns by plotting a graph below, and add some explanation about it

**TODO** - Explore one or more columns by plotting a graph below, and add some explanation about it

**TODO** - Explore one or more columns by plotting a graph below, and add some explanation about it

## Asking and Answering Questions

TODO - write some explanation here.

> Instructions (delete this cell)
>
> - Ask at least 5 interesting questions about your dataset
> - Answer the questions either by computing the results using Numpy/Pandas or by plotting graphs using Matplotlib/Seaborn
> - Create new columns, merge multiple dataset and perform grouping/aggregation wherever necessary
> - Wherever you're using a library function from Pandas/Numpy/Matplotlib etc. explain briefly what it does

#### Q1: TODO - ask a question here and answer it below

#### Q2: TODO - ask a question here and answer it below

#### Q3: TODO - ask a question here and answer it below

#### Q4: TODO - ask a question here and answer it below

#### Q5: TODO - ask a question here and answer it below

## Inferences and Conclusion

**TODO** - Write some explanation here: a summary of all the inferences drawn from the analysis, and any conclusions you may have drawn by answering various questions.

## References and Future Work

**TODO** - Write some explanation here: ideas for future projects using this dataset, and links to resources you found useful.

> Submission Instructions (delete this cell)
>
> To save your work, select "File" > "Save a Copy in Drive" on Google Colab. Once the copy is created, click the "Share" button and select "Anyone with the link" under the "General Access" section to make this notebook publicly accessible.
>
> <img src="https://miro.medium.com/v2/resize:fit:800/format:webp/1*4eXpS4TgIJ6n7obsaUKptQ.png" height="400">
>
>Then, copy the notebook link and submit it on the assignment page.
>
> (Optional) Write a blog post
>
> - A blog post is a great way to present and showcase your work.  
> - Sign up on [Medium.com](https://medium.com) to write a blog post for your project.
> - Copy over the explanations from your Jupyter notebook into your blog post, and [embed code cells & outputs](https://medium.com/jovianml/share-and-embed-jupyter-notebooks-online-with-jovian.com-df709a03064e)
> - Check out the Jovian.ml Medium publication for inspiration: https://medium.com/jovianml